"""Add video process task model

Revision ID: 796f614d8ac3
Revises: 
Create Date: 2025-11-12 01:23:54.968894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796f614d8ac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_process_tasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='任务ID'),
    sa.Column('user_id', sa.String(), nullable=False, comment='用户ID'),
    sa.Column('douyin_id', sa.String(), nullable=True, comment='抖音视频ID（去重用）'),
    sa.Column('original_url', sa.String(), nullable=False, comment='原始视频URL'),
    sa.Column('converted_url', sa.String(), nullable=True, comment='转换后的视频URL（如果适用）'),
    sa.Column('video_path', sa.String(), nullable=True, comment='本地视频文件路径'),
    sa.Column('audio_path', sa.String(), nullable=True, comment='本地音频文件路径'),
    sa.Column('subtitle_text', sa.Text(), nullable=True, comment='语音识别结果（字幕文字）'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI总结结果'),
    sa.Column('status', sa.String(), nullable=False, comment='任务状态：pending-等待处理, processing-处理中, completed-已完成, failed-失败'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.BigInteger(), nullable=True, comment='创建时间戳'),
    sa.Column('updated_at', sa.BigInteger(), nullable=True, comment='更新时间戳'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_process_tasks_douyin_id'), 'video_process_tasks', ['douyin_id'], unique=False)
    op.create_index(op.f('ix_video_process_tasks_status'), 'video_process_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_video_process_tasks_user_id'), 'video_process_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_process_tasks_user_id'), table_name='video_process_tasks')
    op.drop_index(op.f('ix_video_process_tasks_status'), table_name='video_process_tasks')
    op.drop_index(op.f('ix_video_process_tasks_douyin_id'), table_name='video_process_tasks')
    op.drop_table('video_process_tasks')
    # ### end Alembic commands ###
